# Generated by Django 4.2.3 on 2023-10-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audits",
            name="action",
        ),
        migrations.RemoveField(
            model_name="audits",
            name="user",
        ),
        migrations.AddField(
            model_name="audits",
            name="atumus",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AuditTypes",
        ),
    ]
