# Generated by Django 4.2.3 on 2023-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0002_remove_audits_action_remove_audits_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audits",
            name="id_object",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audits",
            name="name_object",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audits",
            name="type_object",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
