# Generated by Django 4.2.3 on 2023-10-04 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0003_audits_id_object_audits_name_object_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Audits",
            new_name="AuditsRemoval",
        ),
    ]
