# Generated by Django 4.2.3 on 2023-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0004_rename_audits_auditsremoval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditsremoval",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auditsremoval",
            name="name_object",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auditsremoval",
            name="type_object",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
