# Generated by Django 4.2.3 on 2023-10-04 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0005_alter_auditsremoval_description_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="auditsremoval",
            table="audits_removal",
        ),
    ]
